### ISSUE TITLE
can't build nativeImage with scala 2.12.6 in build.sbt - but 2.12.4 works fine. 

### ISSUE THREAD

**Issue by russwyte** [OlegIlyenko/sangria-http4s-graalvm-example#1]
For some reason I am seeing this when I run nativeImage:

```
[info] /usr/lib/graalvm/jre/lib/svm/builder/pointsto.jar:/usr/lib/graalvm/jre/lib/svm/builder/svm.jar:/usr/lib/graalvm/jre/lib/svm/builder/objectfile.jar:/usr/lib/graalvm/jre/lib/jvmci/graal.jar:/usr/lib/graalvm/jre/lib/jvmci/jvmci-api.jar:/usr/lib/graalvm/jre/lib/jvmci/jvmci-hotspot.jar:/usr/lib/graalvm/jre/lib/boot/graal-sdk.jar:/usr/lib/graalvm/jre/lib/boot/graaljs-scriptengine.jar:/usr/lib/graalvm/jre/lib/svm/library-support.jar:/project/target/lib_managed/jars/org.sangria-graphql/sangria_2.12/sangria_2.12-1.4.2-SNAPSHOT.jar:/project/target/lib_managed/jars/org.parboiled/parboiled_2.12/parboiled_2.12-2.1.4.jar:/project/target/lib_managed/bundles/com.chuusai/shapeless_2.12/shapeless_2.12-2.3.2.jar:/project/target/lib_managed/jars/org.typelevel/macro-compat_2.12/macro-compat_2.12-1.1.1.jar:/project/target/lib_managed/jars/org.sangria-graphql/macro-visit_2.12/macro-visit_2.12-0.1.1.jar:/project/target/lib_managed/jars/org.sangria-graphql/sangria-marshalling-api_2.12/sangria-marshalling-api_2.12-1.0.3.jar:/project/target/lib_managed/jars/org.sangria-graphql/sangria-streaming-api_2.12/sangria-streaming-api_2.12-1.0.0.jar:/project/target/lib_managed/jars/org.sangria-graphql/sangria-circe_2.12/sangria-circe_2.12-1.2.1.jar:/project/target/lib_managed/jars/org.typelevel/machinist_2.12/machinist_2.12-0.6.2.jar:/project/target/lib_managed/jars/org.http4s/http4s-blaze-server_2.12/http4s-blaze-server_2.12-0.18.9.jar:/project/target/lib_managed/jars/org.http4s/http4s-blaze-core_2.12/http4s-blaze-core_2.12-0.18.9.jar:/project/target/lib_managed/jars/org.http4s/http4s-core_2.12/http4s-core_2.12-0.18.9.jar:/project/target/lib_managed/jars/org.typelevel/cats-core_2.12/cats-core_2.12-1.1.0.jar:/project/target/lib_managed/jars/org.typelevel/cats-macros_2.12/cats-macros_2.12-1.1.0.jar:/project/target/lib_managed/jars/org.typelevel/cats-kernel_2.12/cats-kernel_2.12-1.1.0.jar:/project/target/lib_managed/jars/org.typelevel/cats-effect_2.12/cats-effect_2.12-0.10.jar:/project/target/lib_managed/jars/co.fs2/fs2-io_2.12/fs2-io_2.12-0.10.3.jar:/project/target/lib_managed/jars/co.fs2/fs2-core_2.12/fs2-core_2.12-0.10.3.jar:/project/target/lib_managed/jars/co.fs2/fs2-scodec_2.12/fs2-scodec_2.12-0.10.3.jar:/project/target/lib_managed/bundles/org.scodec/scodec-bits_2.12/scodec-bits_2.12-1.1.5.jar:/project/target/lib_managed/jars/org.http4s/http4s-websocket_2.12/http4s-websocket_2.12-0.2.1.jar:/project/target/lib_managed/jars/org.log4s/log4s_2.12/log4s_2.12-1.6.1.jar:/project/target/lib_managed/jars/org.slf4j/slf4j-api/slf4j-api-1.7.25.jar:/project/target/lib_managed/jars/org.http4s/parboiled_2.12/parboiled_2.12-1.0.0.jar:/project/target/lib_managed/jars/org.http4s/blaze-http_2.12/blaze-http_2.12-0.12.13.jar:/project/target/lib_managed/jars/org.http4s/blaze-core_2.12/blaze-core_2.12-0.12.13.jar:/project/target/lib_managed/jars/com.twitter/hpack/hpack-1.0.2.jar:/project/target/lib_managed/jars/org.eclipse.jetty.alpn/alpn-api/alpn-api-1.1.3.v20160715.jar:/project/target/lib_managed/bundles/org.scala-lang.modules/scala-xml_2.12/scala-xml_2.12-1.0.6.jar:/project/target/lib_managed/jars/org.http4s/http4s-server_2.12/http4s-server_2.12-0.18.9.jar:/project/target/lib_managed/jars/org.http4s/http4s-circe_2.12/http4s-circe_2.12-0.18.9.jar:/project/target/lib_managed/jars/org.http4s/http4s-jawn_2.12/http4s-jawn_2.12-0.18.9.jar:/project/target/lib_managed/jars/org.http4s/jawn-fs2_2.12/jawn-fs2_2.12-0.12.2.jar:/project/target/lib_managed/jars/org.spire-math/jawn-parser_2.12/jawn-parser_2.12-0.11.1.jar:/project/target/lib_managed/jars/io.circe/circe-jawn_2.12/circe-jawn_2.12-0.9.3.jar:/project/target/lib_managed/jars/io.circe/circe-core_2.12/circe-core_2.12-0.9.3.jar:/project/target/lib_managed/jars/io.circe/circe-numbers_2.12/circe-numbers_2.12-0.9.3.jar:/project/target/lib_managed/jars/org.http4s/http4s-dsl_2.12/http4s-dsl_2.12-0.18.9.jar:/project/target/lib_managed/jars/ch.qos.logback/logback-classic/logback-classic-1.2.3.jar:/project/target/lib_managed/jars/ch.qos.logback/logback-core/logback-core-1.2.3.jar:/project/target/lib_managed/jars/io.circe/circe-optics_2.12/circe-optics_2.12-0.9.3.jar:/project/target/lib_managed/jars/com.github.julien-truffaut/monocle-core_2.12/monocle-core_2.12-1.4.0.jar:/project/target/lib_managed/bundles/org.scalaz/scalaz-core_2.12/scalaz-core_2.12-7.2.8.jar:/project/target/scala-2.12/sangria-http4s-graalvm-example_2.12-0.1.0-SNAPSHOT.jar
[info] -H:Path=/project
[info] -H:Name=target/native-image/sangria-http4s-graalvm-example
[info] -H:Class=Main
[info] -H:+ReportUnsupportedElementsAtRuntime
[info] -H:IncludeResources=.*graphiql.*
[info] -H:CLibraryPath=/usr/lib/graalvm/jre/lib/svm/clibraries/linux-amd64
[info] ]
[info]    classlist:  18,969.34 ms
[error] fatal error: java.lang.NoClassDefFoundError: scala/runtime/Nothing$
[error] 	at java.lang.Class.getDeclaredMethods0(Native Method)
[error] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[error] 	at java.lang.Class.getDeclaredMethod(Class.java:2128)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:201)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:337)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:378)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:315)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:396)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:312)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:256)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:216)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: scala.runtime.Nothing$
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	... 14 more
[error] Error: Processing image build request failed
```

**Comment by OlegIlyenko** [comment]
hmmm... it's hard to tell, but maybe scala library is not in the classpath for some reason? I would double-check it.

**Comment by russwyte** [comment]
Thanks! Funny thing though... when I switch to scala 2.12.4 it works fine...

**Comment by russwyte** [comment]
Yes just confirmed in build.sbt:

scalaVersion := "2.12.6" <- always fails for me
but...
scalaVersion := "2.12.4" <- works just fine

**Comment by OlegIlyenko** [comment]
Stumbled upon it myself :D Took a while to figure it out. This should fix the issue: https://github.com/OlegIlyenko/sangria-http4s-graalvm-example/commit/65e84d6c8e00724cfa4ce87edff704e776fb79b6
